version: '3.7'

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
    networks:
      - api_network

  app:
    build: .
    container_name: rentalx
    environment:
      - POSTGRES_HOST=database_ignite
      - POSTGRES_POST=5432
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - api_network

networks:
  api_network:

volumes:
  pgdata:
    driver: local
